### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by mikekrell** [Somi-AI/directus-railway#2]
My Railway container fails to build when I try and update to the most recent commit in the repo. 

When I use commit **Rollback to 10.8, there're bugs in 10.9 release** - e9686f477c5f4ec2594d13e1e21156ffc1983379 , I can build just fine. 

When building with latest commit, the container fails to build with an error 
```
TypeError: String expected

    at /directus/node_modules/.pnpm/knex@3.1.0_pg@8.12.0/node_modules/knex/lib/dialects/sqlite3/index.js:99:18

    at new Promise (<anonymous>)

    at Client_SQLite3.acquireRawConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.12.0/node_modules/knex/lib/dialects/sqlite3/index.js:83:12)

    at create (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.12.0/node_modules/knex/lib/client.js:262:39)
```

**Comment by mikekrell** [comment]
I think it was issue on my part with the DB_CONNECTION_STRING in the ENV from railway. I deployed the template to another container, and them manually pointed the new instance to the old db and everything seems to be OK.
